### ISSUE TITLE
Is this for Arm based Surface RT?

### ISSUE THREAD

**Issue by ShapeShifter499** [alyptik/linux-surfacepro3-rt#1]
I was poking around online and came across this page.   This mentions RT but I'm not finding references to ARM.   Is this being worked on for the ARM Surface RT?

**Comment by alyptik** [comment]
Sorry, no; it's the Linux kernel with realtime patches for the Surface Pro 3 laptop.

**Comment by alyptik** [comment]
No relation to ARM.
